config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'homes#top'
  get '/home/about' => 'homes#about'
  
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end 
  
  resources :users, only:[:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  get '/search', to: 'searches#search'

  resources :chats, only: [:show, :create]
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
    validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
    before_action :authenticate_user!
    
    def create
        @book = Book.find(params[:book_id])
        @book_comment = BookComment.new(book_comment_params)
        @book_comment.book_id = @book.id
        @book_comment.user_id = current_user.id
        unless @book_comment.save
            render 'error'
        end 
    end
    
    def destroy
        @book = Book.find(params[:book_id])
        book_comment = @book.book_comments.find(params[:id])
        book_comment.destroy
    end
    
    private

    def book_comment_params
        params.require(:book_comment).permit(:comment)
    end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_index.html.erb
<% book.book_comments.each do |book_comment| %>
  <% book_comment_user = book_comment.user %>
      <tr>
        <td>
          <%= link_to user_path(book_comment.user), class: "user_#{book_comment_user.id}" do %>
            <%= image_tag book_comment.user.get_profile_image, size: "100x100" %><br>
            <%= book_comment.user.name %>
          <% end %>
        </td>
        <td><%= book_comment.comment %></td>
        <% if current_user == book_comment_user %>
          <td><%= link_to "Destroy", book_book_comment_path(book_comment.book_id, book_comment.id), class: "btn btn-danger", method: :delete, remote: true %></td>
          </%>
        <% end %>
      </tr>
      <% end %>

app/views/book_comments/create.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");

app/views/book_comments/destroy.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");

app/views/book_comments/error.js.erb
// こちらは要件外です。prependはhtmlと違い、子要素の最初に差し込む挙動をします。
$("main > .container").prepend("<%= j(render 'layouts/errors', obj: @book_comment) %>");